repos:
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: check-added-large-files
        args: ['--maxkb=100']
-   repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args:
        - --exclude-file=poetry.lock
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
    -   id: ruff
        args:
        - --fix
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    -   id: black
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
    -   id: mypy
-   repo: local
    hooks:
    -   id: pytest-check
        name: pytest-check
        entry: python3 -m pytest tests/
        language: system
        pass_filenames: false
