name: pytest

on:
  pull_request:
  push:
    
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: snok/install-poetry@v1
    - name: Install dependencies
      run: poetry install --no-root
    - name: Run tests
      run: poetry run pytest --cov juniper tests/
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      with:
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
